NET_ERROR( NET_OK, Sucesso )
NET_ERROR( ERR_UNKNOWN, Erro desconhecido )
NET_ERROR( PS_INIT_PATCHER, Inicializando )
NET_ERROR( PS_CHECK_PATCHER, Confirmando atualizacao do Patcher )
NET_ERROR( PS_CHECK_VERSION, Verificando versao )
NET_ERROR( PS_CONNECT_PATCHSVR, Conectando ao servidor de patch )
NET_ERROR( PS_CONNECT_PATCHSVR_OK, Conexao estabelecida )
NET_ERROR( PS_GET_PATCHLIST, Obtendo lista de atualizacoes )
NET_ERROR( PS_GET_PATCHLIST_OK, Lista obtida )
NET_ERROR( PS_DOWNLOAD_PATCH, Baixando atualizacoes )
NET_ERROR( PS_DOWNLOAD_PATCH_OK, Download concluido )
NET_ERROR( PS_APPLY_PATCH, Aplicando atualizacoes )
NET_ERROR( PS_APPLY_PATCH_OK, Aplicacao concluida )
NET_ERROR( PS_COMPLETE_PATCH, Patch completo )
NET_ERROR( PS_COMPLETE_PATCH_OK, Patch concluido com sucesso )
NET_ERROR( PS_CANCEL_PATCH, Cancelando patch )
NET_ERROR( PS_CANCEL_PATCH_OK, Patch cancelado )
NET_ERROR( PS_ERROR_PATCH, Erro durante patch )
NET_ERROR( PS_ERROR_PATCH_OK, Erro de patch detectado )
NET_ERROR( PS_PATCHER_PATCH, Atualizando Patcher )
NET_ERROR( PS_PROGRAMPATH_ERR, Nao foi possivel encontrar arquivo )
NET_ERROR( PS_WEBOPEN_ERR, Erro na conexao de rede )
NET_ERROR( PS_PATCHSRC_ERR, Falha na conexao com servidor de patch )
NET_ERROR( PS_DOWN_PATCHPATH_ERR, Falha no download de arquivo de patch )
NET_ERROR( PS_PATCHPATH_READ_ERR, Falha na leitura do arquivo de patch )
NET_ERROR( PS_NEWVER_DOWN_ERR, Falha no download de versao )
NET_ERROR( PS_VER_READ_ERR, Erro na versao de programa )
NET_ERROR( PS_PATCHSTR, Falha na leitura de texto )
NET_ERROR( PS_IMAGE_NO_EXIST, IMAGE.KOM nao existe )
NET_ERROR( PS_IMAGE_NO_LOAD, IMAGE.KOM nao carregou )
NET_ERROR( PS_PATCHTIME_MSG, Mensagem de tempo de patch )
NET_ERROR( PS_EXECUTE_IN_SYSTEM_FOLDER, Executar na pasta do sistema )
NET_ERROR( ERR_SENTINEL, Sentinel )
