# Other server projects CMakeLists.txt files

# WUDPRelay
add_executable(WUDPRelay WIN32)
file(GLOB_RECURSE WUDPRELAY_SOURCES "WUDPRelay/*.cpp" "WUDPRelay/*.h")
target_sources(WUDPRelay PRIVATE ${WUDPRELAY_SOURCES})
target_include_directories(WUDPRelay PRIVATE ${COMMON_INCLUDES} "${CMAKE_CURRENT_SOURCE_DIR}/WUDPRelay")
target_link_libraries(WUDPRelay PRIVATE ServerCommon ${COMMON_LIBS})
target_compile_definitions(WUDPRelay PRIVATE WIN32 _WINDOWS UNICODE _UNICODE)
if(PLATFORM_X64)
    target_compile_definitions(WUDPRelay PRIVATE WIN64)
else()
    target_compile_definitions(WUDPRelay PRIVATE _USE_32BIT_TIME_T)
endif()

# GCServerManager_Battle
add_executable(GCServerManager WIN32)
file(GLOB_RECURSE GCSERVERMANAGER_SOURCES "GCServerManager_Battle/*.cpp" "GCServerManager_Battle/*.h")
target_sources(GCServerManager PRIVATE ${GCSERVERMANAGER_SOURCES})
target_include_directories(GCServerManager PRIVATE ${COMMON_INCLUDES} "${CMAKE_CURRENT_SOURCE_DIR}/GCServerManager_Battle")
target_link_libraries(GCServerManager PRIVATE ServerCommon ${COMMON_LIBS})
target_compile_definitions(GCServerManager PRIVATE WIN32 _WINDOWS UNICODE _UNICODE)
if(PLATFORM_X64)
    target_compile_definitions(GCServerManager PRIVATE WIN64)
else()
    target_compile_definitions(GCServerManager PRIVATE _USE_32BIT_TIME_T)
endif()

# MatchServer
add_executable(MatchServer WIN32)
file(GLOB_RECURSE MATCHSERVER_SOURCES "MatchServer/*.cpp" "MatchServer/*.h")
target_sources(MatchServer PRIVATE ${MATCHSERVER_SOURCES})
target_include_directories(MatchServer PRIVATE ${COMMON_INCLUDES} "${CMAKE_CURRENT_SOURCE_DIR}/MatchServer")
target_link_libraries(MatchServer PRIVATE ServerCommon ${COMMON_LIBS})
target_compile_definitions(MatchServer PRIVATE WIN32 _WINDOWS UNICODE _UNICODE)
if(PLATFORM_X64)
    target_compile_definitions(MatchServer PRIVATE WIN64)
else()
    target_compile_definitions(MatchServer PRIVATE _USE_32BIT_TIME_T)
endif()

# WTCPRelay
add_executable(WTRServer WIN32)
file(GLOB_RECURSE WTRSERVER_SOURCES "WTCPRelay/*.cpp" "WTCPRelay/*.h")
target_sources(WTRServer PRIVATE ${WTRSERVER_SOURCES})
target_include_directories(WTRServer PRIVATE ${COMMON_INCLUDES} "${CMAKE_CURRENT_SOURCE_DIR}/WTCPRelay")
target_link_libraries(WTRServer PRIVATE ServerCommon ${COMMON_LIBS})
target_compile_definitions(WTRServer PRIVATE WIN32 _WINDOWS UNICODE _UNICODE)
if(PLATFORM_X64)
    target_compile_definitions(WTRServer PRIVATE WIN64)
else()
    target_compile_definitions(WTRServer PRIVATE _USE_32BIT_TIME_T)
endif()

# WMsgServer
add_executable(WMsgServer WIN32)
file(GLOB_RECURSE WMSGSERVER_SOURCES "WMsgServer/*.cpp" "WMsgServer/*.h")
target_sources(WMsgServer PRIVATE ${WMSGSERVER_SOURCES})
target_include_directories(WMsgServer PRIVATE ${COMMON_INCLUDES} "${CMAKE_CURRENT_SOURCE_DIR}/WMsgServer")
target_link_libraries(WMsgServer PRIVATE ServerCommon ${COMMON_LIBS})
target_compile_definitions(WMsgServer PRIVATE WIN32 _WINDOWS UNICODE _UNICODE)
if(PLATFORM_X64)
    target_compile_definitions(WMsgServer PRIVATE WIN64)
else()
    target_compile_definitions(WMsgServer PRIVATE _USE_32BIT_TIME_T)
endif()

# UnitTest
add_executable(UnitTest WIN32)
file(GLOB_RECURSE UNITTEST_SOURCES "UnitTest/*.cpp" "UnitTest/*.h")
target_sources(UnitTest PRIVATE ${UNITTEST_SOURCES})
target_include_directories(UnitTest PRIVATE ${COMMON_INCLUDES} "${CMAKE_CURRENT_SOURCE_DIR}/UnitTest")
target_link_libraries(UnitTest PRIVATE ServerCommon ${COMMON_LIBS})
target_compile_definitions(UnitTest PRIVATE WIN32 _WINDOWS UNICODE _UNICODE)
if(PLATFORM_X64)
    target_compile_definitions(UnitTest PRIVATE WIN64)
else()
    target_compile_definitions(UnitTest PRIVATE _USE_32BIT_TIME_T)
endif()
